apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config-map
  labels:
    app: postgres-config-map
data:
  POSTGRES_DB_HOST: postgres
  POSTGRES_DB_STUDENT: student_microservice
  POSTGRES_DB_TUITION: tuition_microservice
  POSTGRES_DB_TEST_SCORE: test_score_microservice