apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-score-deployment
  labels:
    app: test-score-deployment
spec:
  selector:
    matchLabels:
      app: test-score-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: test-score-deployment
    spec:
      containers:
        - name: topeducation-test-score-postgres
          image: jmoragacalvo/topeducation-score-service:latest
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_CLOUD_CONFIG_URI
              value: http://config-service:8081
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: http://eureka-service:8761
            - name: eureka.instance.preferIpAddress
              value: "true"
            - name: POSTGRES_DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: POSTGRES_DB_HOST
            - name: POSTGRES_DB_TEST_SCORE
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: POSTGRES_DB_TEST_SCORE
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: POSTGRES_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: test-score-service
  labels:
    app: test-score-service
spec:
  selector:
    app: test-score-deployment
  ports:
    - protocol: TCP
      port: 8084
      targetPort: 8084
  type: LoadBalancer